import{S as p,N as m,P as g,a as y}from"./assets/vendor-Biouwi_g.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function b(){const t="#764191",n="#FFFFFF";document.querySelectorAll(".star-rating").forEach(s=>{const e=Number(s.dataset.rating)||0;s.querySelectorAll(".star-rating__star").forEach((a,f)=>{a.style.backgroundColor=f<e?t:n})})}function v(){new p(".feedback-swiper",h)}const h={modules:[m,g],loop:!1,slidesPerView:1,spaceBetween:20,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,bulletClass:"custom-bullet",bulletActiveClass:"custom-bullet-active",renderBullet(t,n){return t>2?"":`<span class="${n}"></span>`}},on:{init(){c(this),b()},slideChange(){c(this)}}};function c(t){const n=t.slides.length,o=t.activeIndex,s=document.querySelectorAll(".custom-bullet");if(!s.length||n===0)return;let e;o===0?e=0:o===n-1?e=2:e=1,s.forEach((r,a)=>r.classList.toggle("custom-bullet-active",a===e))}const L="https://sound-wave.b.goit.study/api";async function w(){const{data:{data:t}}=await y.get(`${L}/feedbacks`,{params:{limit:10}});return Array.isArray(t)?t:[]}const l=document.querySelector("#feedback-list");async function S(){if(!l)return;const t=await w();!Array.isArray(t)||t.length===0||(l.innerHTML=t.map(n=>`<div class="swiper-slide">${k(n)}</div>`).join(""),v())}window.addEventListener("DOMContentLoaded",()=>{S()});function k({rating:t,descr:n,name:o}){return`
    <div class="feedback-card">
      <div class="star-rating star-rating--sm" data-rating="${Math.round(t)}">
        ${'<span class="star-rating__star"></span>'.repeat(5)}
      </div>
      <p class="feedback-text">${n}</p>
      <p class="feedback-author">${o}</p>
    </div>
  `}const u=document.querySelector("[data-menu]"),E=document.querySelector("[data-menu-open]"),O=document.querySelector("[data-menu-close]"),q=document.querySelectorAll("[data-mob-nav]"),d=()=>{u.classList.toggle("visually-hidden")},i=()=>{d(),document.body.classList.remove("no-scroll")};E.addEventListener("click",d);O.addEventListener("click",i);q.forEach(t=>{t.addEventListener("click",()=>{i()})});document.addEventListener("keydown",t=>{t.key==="Escape"&&!u.classList.contains("visually-hidden")&&i()});document.querySelector(".btn-load-more");document.querySelector(".loader");
//# sourceMappingURL=index.js.map
