import{S as p,N as m,P as g,i as y,a as b}from"./assets/vendor-BRq3c0uS.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function v(){const e="#764191",n="#FFFFFF";document.querySelectorAll(".star-rating").forEach(s=>{const t=Number(s.dataset.rating)||0;s.querySelectorAll(".star-rating__star").forEach((a,f)=>{a.style.backgroundColor=f<t?e:n})})}function h(){new p(".feedback-swiper",L)}const L={modules:[m,g],loop:!1,slidesPerView:1,spaceBetween:20,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,bulletClass:"custom-bullet",bulletActiveClass:"custom-bullet-active",renderBullet(e,n){return e>2?"":`<span class="${n}"></span>`}},on:{init(){c(this),v()},slideChange(){c(this)}}};function c(e){const n=e.slides.length,o=e.activeIndex,s=document.querySelectorAll(".custom-bullet");if(!s.length||n===0)return;let t;o===0?t=0:o===n-1?t=2:t=1,s.forEach((r,a)=>r.classList.toggle("custom-bullet-active",a===t))}function w({title:e,message:n}){y.show({title:e,titleColor:"red",message:n,position:"topCenter",messageColor:"black",color:"red"})}const k="https://sound-wave.b.goit.study/api",S="/feedbacks",E=`${k}${S}`,O={params:{limit:10}};async function q(){try{const{data:{data:e}}=await b.get(E,O);return Array.isArray(e)?e:[]}catch(e){return w(e.message),[]}}const l=document.querySelector("#feedback-list");async function A(){if(!l)return;const e=await q();!Array.isArray(e)||e.length===0||(l.innerHTML=e.map(n=>`<div class="swiper-slide">${F(n)}</div>`).join(""),h())}window.addEventListener("DOMContentLoaded",()=>{A()});function F({rating:e,descr:n,name:o}){return`
    <div class="feedback-card">
      <div class="star-rating star-rating--sm" data-rating="${Math.round(e)}">
        ${'<span class="star-rating__star"></span>'.repeat(5)}
      </div>
      <p class="feedback-text">${n}</p>
      <p class="feedback-author">${o}</p>
    </div>
  `}const u=document.querySelector("[data-menu]"),C=document.querySelector("[data-menu-open]"),M=document.querySelector("[data-menu-close]"),N=document.querySelectorAll("[data-mob-nav]"),d=()=>{u.classList.toggle("visually-hidden")},i=()=>{d(),document.body.classList.remove("no-scroll")};C.addEventListener("click",d);M.addEventListener("click",i);N.forEach(e=>{e.addEventListener("click",()=>{i()})});document.addEventListener("keydown",e=>{e.key==="Escape"&&!u.classList.contains("visually-hidden")&&i()});document.querySelector(".btn-load-more");document.querySelector(".loader");
//# sourceMappingURL=index.js.map
