import{S as u,N as d,P as f,i as p,a as g}from"./assets/vendor-BRq3c0uS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();function m(){const t="#764191",r="#FFFFFF";document.querySelectorAll(".star-rating").forEach(n=>{const e=Number(n.dataset.rating)||0;n.querySelectorAll(".star-rating__star").forEach((a,l)=>{a.style.backgroundColor=l<e?t:r})})}function b(){new u(".feedback-swiper",y)}const y={modules:[d,f],loop:!1,slidesPerView:1,spaceBetween:20,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,bulletClass:"custom-bullet",bulletActiveClass:"custom-bullet-active",renderBullet(t,r){return t>2?"":`<span class="${r}"></span>`}},on:{init(){i(this),m()},slideChange(){i(this)}}};function i(t){const r=t.slides.length,o=t.activeIndex,n=document.querySelectorAll(".custom-bullet");if(!n.length||r===0)return;let e;o===0?e=0:o===r-1?e=2:e=1,n.forEach((s,a)=>s.classList.toggle("custom-bullet-active",a===e))}function h({title:t,message:r}){p.show({title:t,titleColor:"red",message:r,position:"topCenter",messageColor:"black",color:"red"})}const v="https://sound-wave.b.goit.study/api",w="/feedbacks",L=`${v}${w}`,O={params:{limit:10}};async function S(){try{const{data:{data:t}}=await g.get(L,O);return Array.isArray(t)?t:[]}catch(t){return h(t.message),[]}}const c=document.querySelector("#feedback-list");async function F(){if(!c)return;const t=await S();!Array.isArray(t)||t.length===0||(c.innerHTML=t.map(r=>`<div class="swiper-slide">${k(r)}</div>`).join(""),b())}window.addEventListener("DOMContentLoaded",()=>{F()});function k({rating:t,descr:r,name:o}){return`
    <div class="feedback-card">
      <div class="star-rating star-rating--sm" data-rating="${Math.round(t)}">
        ${'<span class="star-rating__star"></span>'.repeat(5)}
      </div>
      <p class="feedback-text">${r}</p>
      <p class="feedback-author">${o}</p>
    </div>
  `}document.querySelector(".btn-load-more");document.querySelector(".loader");
//# sourceMappingURL=index.js.map
